# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import hololib_pb2 as hololib__pb2

GRPC_GENERATED_VERSION = '1.65.5'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in hololib_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class GreeterStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/hololibgrpc.Greeter/SayHello',
                request_serializer=hololib__pb2.HelloRequest.SerializeToString,
                response_deserializer=hololib__pb2.HelloReply.FromString,
                _registered_method=True)
        self.SayHelloAgain = channel.unary_unary(
                '/hololibgrpc.Greeter/SayHelloAgain',
                request_serializer=hololib__pb2.HelloRequest.SerializeToString,
                response_deserializer=hololib__pb2.HelloReply.FromString,
                _registered_method=True)
        self.ComputeHologram = channel.unary_unary(
                '/hololibgrpc.Greeter/ComputeHologram',
                request_serializer=hololib__pb2.HologramRequest.SerializeToString,
                response_deserializer=hololib__pb2.HologramReply.FromString,
                _registered_method=True)
        self.ComputeHologram_stream = channel.unary_stream(
                '/hololibgrpc.Greeter/ComputeHologram_stream',
                request_serializer=hololib__pb2.HologramRequest.SerializeToString,
                response_deserializer=hololib__pb2.HologramReply.FromString,
                _registered_method=True)


class GreeterServicer(object):
    """The greeting service definition.
    """

    def SayHello(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHelloAgain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputeHologram(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputeHologram_stream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=hololib__pb2.HelloRequest.FromString,
                    response_serializer=hololib__pb2.HelloReply.SerializeToString,
            ),
            'SayHelloAgain': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHelloAgain,
                    request_deserializer=hololib__pb2.HelloRequest.FromString,
                    response_serializer=hololib__pb2.HelloReply.SerializeToString,
            ),
            'ComputeHologram': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeHologram,
                    request_deserializer=hololib__pb2.HologramRequest.FromString,
                    response_serializer=hololib__pb2.HologramReply.SerializeToString,
            ),
            'ComputeHologram_stream': grpc.unary_stream_rpc_method_handler(
                    servicer.ComputeHologram_stream,
                    request_deserializer=hololib__pb2.HologramRequest.FromString,
                    response_serializer=hololib__pb2.HologramReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hololibgrpc.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hololibgrpc.Greeter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """The greeting service definition.
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hololibgrpc.Greeter/SayHello',
            hololib__pb2.HelloRequest.SerializeToString,
            hololib__pb2.HelloReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SayHelloAgain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hololibgrpc.Greeter/SayHelloAgain',
            hololib__pb2.HelloRequest.SerializeToString,
            hololib__pb2.HelloReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputeHologram(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hololibgrpc.Greeter/ComputeHologram',
            hololib__pb2.HologramRequest.SerializeToString,
            hololib__pb2.HologramReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputeHologram_stream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hololibgrpc.Greeter/ComputeHologram_stream',
            hololib__pb2.HologramRequest.SerializeToString,
            hololib__pb2.HologramReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
