# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hololib.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rhololib.proto\x12\x0bhololibgrpc\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\xff\x01\n\x0fHologramRequest\x12\x14\n\x0cmeshDataSize\x18\x01 \x01(\r\x12\x10\n\x08meshData\x18\x02 \x01(\x0c\x12\x17\n\x0ftextureDataSize\x18\x03 \x01(\r\x12\x13\n\x0btextureData\x18\x04 \x01(\x0c\x12\x15\n\rshadingOption\x18\x05 \x01(\t\x12\x15\n\rtextureOption\x18\x06 \x01(\t\x12\x18\n\x10wavelengthOption\x18\x07 \x01(\t\x12\x17\n\x0fpixelSizeOption\x18\x08 \x01(\t\x12\x19\n\x11numOfPixelsOption\x18\t \x01(\t\x12\x1a\n\x12initialPhaseOption\x18\n \x01(\t\"\x7f\n\rHologramReply\x12\x18\n\x10hologramDataSize\x18\x01 \x01(\r\x12\x14\n\x0chologramData\x18\x02 \x01(\x0c\x12\x17\n\x0fReconstDataSize\x18\x03 \x01(\r\x12\x13\n\x0bReconstData\x18\x04 \x01(\x0c\x12\x10\n\x08\x64uration\x18\x05 \x01(\r2\xb9\x02\n\x07Greeter\x12@\n\x08SayHello\x12\x19.hololibgrpc.HelloRequest\x1a\x17.hololibgrpc.HelloReply\"\x00\x12\x45\n\rSayHelloAgain\x12\x19.hololibgrpc.HelloRequest\x1a\x17.hololibgrpc.HelloReply\"\x00\x12M\n\x0f\x43omputeHologram\x12\x1c.hololibgrpc.HologramRequest\x1a\x1a.hololibgrpc.HologramReply\"\x00\x12V\n\x16\x43omputeHologram_stream\x12\x1c.hololibgrpc.HologramRequest\x1a\x1a.hololibgrpc.HologramReply\"\x00\x30\x01\x42\x1fZ\x1d./grpc-cmd-client/hololibgrpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hololib_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\035./grpc-cmd-client/hololibgrpc'
  _globals['_HELLOREQUEST']._serialized_start=30
  _globals['_HELLOREQUEST']._serialized_end=58
  _globals['_HELLOREPLY']._serialized_start=60
  _globals['_HELLOREPLY']._serialized_end=89
  _globals['_HOLOGRAMREQUEST']._serialized_start=92
  _globals['_HOLOGRAMREQUEST']._serialized_end=347
  _globals['_HOLOGRAMREPLY']._serialized_start=349
  _globals['_HOLOGRAMREPLY']._serialized_end=476
  _globals['_GREETER']._serialized_start=479
  _globals['_GREETER']._serialized_end=792
# @@protoc_insertion_point(module_scope)
