// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: hololib.proto
// Original file comments:
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_hololib_2eproto__INCLUDED
#define GRPC_hololib_2eproto__INCLUDED

#include "hololib.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace hololibgrpc {

// The greeting service definition.
class Greeter final {
 public:
  static constexpr char const* service_full_name() {
    return "hololibgrpc.Greeter";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends a greeting
    virtual ::grpc::Status SayHello(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest& request, ::hololibgrpc::HelloReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hololibgrpc::HelloReply>> AsyncSayHello(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hololibgrpc::HelloReply>>(AsyncSayHelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hololibgrpc::HelloReply>> PrepareAsyncSayHello(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hololibgrpc::HelloReply>>(PrepareAsyncSayHelloRaw(context, request, cq));
    }
    virtual ::grpc::Status SayHelloAgain(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest& request, ::hololibgrpc::HelloReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hololibgrpc::HelloReply>> AsyncSayHelloAgain(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hololibgrpc::HelloReply>>(AsyncSayHelloAgainRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hololibgrpc::HelloReply>> PrepareAsyncSayHelloAgain(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hololibgrpc::HelloReply>>(PrepareAsyncSayHelloAgainRaw(context, request, cq));
    }
    virtual ::grpc::Status ComputeHologram(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest& request, ::hololibgrpc::HologramReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hololibgrpc::HologramReply>> AsyncComputeHologram(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hololibgrpc::HologramReply>>(AsyncComputeHologramRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hololibgrpc::HologramReply>> PrepareAsyncComputeHologram(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hololibgrpc::HologramReply>>(PrepareAsyncComputeHologramRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::hololibgrpc::HologramReply>> ComputeHologram_stream(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::hololibgrpc::HologramReply>>(ComputeHologram_streamRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::hololibgrpc::HologramReply>> AsyncComputeHologram_stream(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::hololibgrpc::HologramReply>>(AsyncComputeHologram_streamRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::hololibgrpc::HologramReply>> PrepareAsyncComputeHologram_stream(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::hololibgrpc::HologramReply>>(PrepareAsyncComputeHologram_streamRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Sends a greeting
      virtual void SayHello(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest* request, ::hololibgrpc::HelloReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SayHello(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest* request, ::hololibgrpc::HelloReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void SayHelloAgain(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest* request, ::hololibgrpc::HelloReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SayHelloAgain(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest* request, ::hololibgrpc::HelloReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ComputeHologram(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest* request, ::hololibgrpc::HologramReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ComputeHologram(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest* request, ::hololibgrpc::HologramReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ComputeHologram_stream(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest* request, ::grpc::ClientReadReactor< ::hololibgrpc::HologramReply>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::hololibgrpc::HelloReply>* AsyncSayHelloRaw(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::hololibgrpc::HelloReply>* PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::hololibgrpc::HelloReply>* AsyncSayHelloAgainRaw(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::hololibgrpc::HelloReply>* PrepareAsyncSayHelloAgainRaw(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::hololibgrpc::HologramReply>* AsyncComputeHologramRaw(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::hololibgrpc::HologramReply>* PrepareAsyncComputeHologramRaw(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::hololibgrpc::HologramReply>* ComputeHologram_streamRaw(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::hololibgrpc::HologramReply>* AsyncComputeHologram_streamRaw(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::hololibgrpc::HologramReply>* PrepareAsyncComputeHologram_streamRaw(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SayHello(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest& request, ::hololibgrpc::HelloReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hololibgrpc::HelloReply>> AsyncSayHello(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hololibgrpc::HelloReply>>(AsyncSayHelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hololibgrpc::HelloReply>> PrepareAsyncSayHello(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hololibgrpc::HelloReply>>(PrepareAsyncSayHelloRaw(context, request, cq));
    }
    ::grpc::Status SayHelloAgain(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest& request, ::hololibgrpc::HelloReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hololibgrpc::HelloReply>> AsyncSayHelloAgain(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hololibgrpc::HelloReply>>(AsyncSayHelloAgainRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hololibgrpc::HelloReply>> PrepareAsyncSayHelloAgain(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hololibgrpc::HelloReply>>(PrepareAsyncSayHelloAgainRaw(context, request, cq));
    }
    ::grpc::Status ComputeHologram(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest& request, ::hololibgrpc::HologramReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hololibgrpc::HologramReply>> AsyncComputeHologram(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hololibgrpc::HologramReply>>(AsyncComputeHologramRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hololibgrpc::HologramReply>> PrepareAsyncComputeHologram(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hololibgrpc::HologramReply>>(PrepareAsyncComputeHologramRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::hololibgrpc::HologramReply>> ComputeHologram_stream(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::hololibgrpc::HologramReply>>(ComputeHologram_streamRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::hololibgrpc::HologramReply>> AsyncComputeHologram_stream(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::hololibgrpc::HologramReply>>(AsyncComputeHologram_streamRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::hololibgrpc::HologramReply>> PrepareAsyncComputeHologram_stream(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::hololibgrpc::HologramReply>>(PrepareAsyncComputeHologram_streamRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SayHello(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest* request, ::hololibgrpc::HelloReply* response, std::function<void(::grpc::Status)>) override;
      void SayHello(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest* request, ::hololibgrpc::HelloReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SayHelloAgain(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest* request, ::hololibgrpc::HelloReply* response, std::function<void(::grpc::Status)>) override;
      void SayHelloAgain(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest* request, ::hololibgrpc::HelloReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ComputeHologram(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest* request, ::hololibgrpc::HologramReply* response, std::function<void(::grpc::Status)>) override;
      void ComputeHologram(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest* request, ::hololibgrpc::HologramReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ComputeHologram_stream(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest* request, ::grpc::ClientReadReactor< ::hololibgrpc::HologramReply>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::hololibgrpc::HelloReply>* AsyncSayHelloRaw(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::hololibgrpc::HelloReply>* PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::hololibgrpc::HelloReply>* AsyncSayHelloAgainRaw(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::hololibgrpc::HelloReply>* PrepareAsyncSayHelloAgainRaw(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::hololibgrpc::HologramReply>* AsyncComputeHologramRaw(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::hololibgrpc::HologramReply>* PrepareAsyncComputeHologramRaw(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::hololibgrpc::HologramReply>* ComputeHologram_streamRaw(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest& request) override;
    ::grpc::ClientAsyncReader< ::hololibgrpc::HologramReply>* AsyncComputeHologram_streamRaw(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::hololibgrpc::HologramReply>* PrepareAsyncComputeHologram_streamRaw(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SayHello_;
    const ::grpc::internal::RpcMethod rpcmethod_SayHelloAgain_;
    const ::grpc::internal::RpcMethod rpcmethod_ComputeHologram_;
    const ::grpc::internal::RpcMethod rpcmethod_ComputeHologram_stream_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends a greeting
    virtual ::grpc::Status SayHello(::grpc::ServerContext* context, const ::hololibgrpc::HelloRequest* request, ::hololibgrpc::HelloReply* response);
    virtual ::grpc::Status SayHelloAgain(::grpc::ServerContext* context, const ::hololibgrpc::HelloRequest* request, ::hololibgrpc::HelloReply* response);
    virtual ::grpc::Status ComputeHologram(::grpc::ServerContext* context, const ::hololibgrpc::HologramRequest* request, ::hololibgrpc::HologramReply* response);
    virtual ::grpc::Status ComputeHologram_stream(::grpc::ServerContext* context, const ::hololibgrpc::HologramRequest* request, ::grpc::ServerWriter< ::hololibgrpc::HologramReply>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SayHello() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::hololibgrpc::HelloRequest* /*request*/, ::hololibgrpc::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHello(::grpc::ServerContext* context, ::hololibgrpc::HelloRequest* request, ::grpc::ServerAsyncResponseWriter< ::hololibgrpc::HelloReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SayHelloAgain : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SayHelloAgain() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_SayHelloAgain() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHelloAgain(::grpc::ServerContext* /*context*/, const ::hololibgrpc::HelloRequest* /*request*/, ::hololibgrpc::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHelloAgain(::grpc::ServerContext* context, ::hololibgrpc::HelloRequest* request, ::grpc::ServerAsyncResponseWriter< ::hololibgrpc::HelloReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ComputeHologram : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ComputeHologram() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_ComputeHologram() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ComputeHologram(::grpc::ServerContext* /*context*/, const ::hololibgrpc::HologramRequest* /*request*/, ::hololibgrpc::HologramReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestComputeHologram(::grpc::ServerContext* context, ::hololibgrpc::HologramRequest* request, ::grpc::ServerAsyncResponseWriter< ::hololibgrpc::HologramReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ComputeHologram_stream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ComputeHologram_stream() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_ComputeHologram_stream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ComputeHologram_stream(::grpc::ServerContext* /*context*/, const ::hololibgrpc::HologramRequest* /*request*/, ::grpc::ServerWriter< ::hololibgrpc::HologramReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestComputeHologram_stream(::grpc::ServerContext* context, ::hololibgrpc::HologramRequest* request, ::grpc::ServerAsyncWriter< ::hololibgrpc::HologramReply>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(3, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SayHello<WithAsyncMethod_SayHelloAgain<WithAsyncMethod_ComputeHologram<WithAsyncMethod_ComputeHologram_stream<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SayHello() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::hololibgrpc::HelloRequest, ::hololibgrpc::HelloReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::hololibgrpc::HelloRequest* request, ::hololibgrpc::HelloReply* response) { return this->SayHello(context, request, response); }));}
    void SetMessageAllocatorFor_SayHello(
        ::grpc::MessageAllocator< ::hololibgrpc::HelloRequest, ::hololibgrpc::HelloReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::hololibgrpc::HelloRequest, ::hololibgrpc::HelloReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::hololibgrpc::HelloRequest* /*request*/, ::hololibgrpc::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SayHello(
      ::grpc::CallbackServerContext* /*context*/, const ::hololibgrpc::HelloRequest* /*request*/, ::hololibgrpc::HelloReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SayHelloAgain : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SayHelloAgain() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::hololibgrpc::HelloRequest, ::hololibgrpc::HelloReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::hololibgrpc::HelloRequest* request, ::hololibgrpc::HelloReply* response) { return this->SayHelloAgain(context, request, response); }));}
    void SetMessageAllocatorFor_SayHelloAgain(
        ::grpc::MessageAllocator< ::hololibgrpc::HelloRequest, ::hololibgrpc::HelloReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::hololibgrpc::HelloRequest, ::hololibgrpc::HelloReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SayHelloAgain() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHelloAgain(::grpc::ServerContext* /*context*/, const ::hololibgrpc::HelloRequest* /*request*/, ::hololibgrpc::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SayHelloAgain(
      ::grpc::CallbackServerContext* /*context*/, const ::hololibgrpc::HelloRequest* /*request*/, ::hololibgrpc::HelloReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ComputeHologram : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ComputeHologram() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::hololibgrpc::HologramRequest, ::hololibgrpc::HologramReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::hololibgrpc::HologramRequest* request, ::hololibgrpc::HologramReply* response) { return this->ComputeHologram(context, request, response); }));}
    void SetMessageAllocatorFor_ComputeHologram(
        ::grpc::MessageAllocator< ::hololibgrpc::HologramRequest, ::hololibgrpc::HologramReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::hololibgrpc::HologramRequest, ::hololibgrpc::HologramReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ComputeHologram() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ComputeHologram(::grpc::ServerContext* /*context*/, const ::hololibgrpc::HologramRequest* /*request*/, ::hololibgrpc::HologramReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ComputeHologram(
      ::grpc::CallbackServerContext* /*context*/, const ::hololibgrpc::HologramRequest* /*request*/, ::hololibgrpc::HologramReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ComputeHologram_stream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ComputeHologram_stream() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackServerStreamingHandler< ::hololibgrpc::HologramRequest, ::hololibgrpc::HologramReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::hololibgrpc::HologramRequest* request) { return this->ComputeHologram_stream(context, request); }));
    }
    ~WithCallbackMethod_ComputeHologram_stream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ComputeHologram_stream(::grpc::ServerContext* /*context*/, const ::hololibgrpc::HologramRequest* /*request*/, ::grpc::ServerWriter< ::hololibgrpc::HologramReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::hololibgrpc::HologramReply>* ComputeHologram_stream(
      ::grpc::CallbackServerContext* /*context*/, const ::hololibgrpc::HologramRequest* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SayHello<WithCallbackMethod_SayHelloAgain<WithCallbackMethod_ComputeHologram<WithCallbackMethod_ComputeHologram_stream<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SayHello() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::hololibgrpc::HelloRequest* /*request*/, ::hololibgrpc::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SayHelloAgain : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SayHelloAgain() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_SayHelloAgain() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHelloAgain(::grpc::ServerContext* /*context*/, const ::hololibgrpc::HelloRequest* /*request*/, ::hololibgrpc::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ComputeHologram : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ComputeHologram() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_ComputeHologram() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ComputeHologram(::grpc::ServerContext* /*context*/, const ::hololibgrpc::HologramRequest* /*request*/, ::hololibgrpc::HologramReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ComputeHologram_stream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ComputeHologram_stream() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_ComputeHologram_stream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ComputeHologram_stream(::grpc::ServerContext* /*context*/, const ::hololibgrpc::HologramRequest* /*request*/, ::grpc::ServerWriter< ::hololibgrpc::HologramReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SayHello() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::hololibgrpc::HelloRequest* /*request*/, ::hololibgrpc::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHello(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SayHelloAgain : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SayHelloAgain() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_SayHelloAgain() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHelloAgain(::grpc::ServerContext* /*context*/, const ::hololibgrpc::HelloRequest* /*request*/, ::hololibgrpc::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHelloAgain(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ComputeHologram : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ComputeHologram() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_ComputeHologram() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ComputeHologram(::grpc::ServerContext* /*context*/, const ::hololibgrpc::HologramRequest* /*request*/, ::hololibgrpc::HologramReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestComputeHologram(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ComputeHologram_stream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ComputeHologram_stream() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_ComputeHologram_stream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ComputeHologram_stream(::grpc::ServerContext* /*context*/, const ::hololibgrpc::HologramRequest* /*request*/, ::grpc::ServerWriter< ::hololibgrpc::HologramReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestComputeHologram_stream(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(3, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SayHello() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SayHello(context, request, response); }));
    }
    ~WithRawCallbackMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::hololibgrpc::HelloRequest* /*request*/, ::hololibgrpc::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SayHello(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SayHelloAgain : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SayHelloAgain() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SayHelloAgain(context, request, response); }));
    }
    ~WithRawCallbackMethod_SayHelloAgain() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHelloAgain(::grpc::ServerContext* /*context*/, const ::hololibgrpc::HelloRequest* /*request*/, ::hololibgrpc::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SayHelloAgain(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ComputeHologram : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ComputeHologram() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ComputeHologram(context, request, response); }));
    }
    ~WithRawCallbackMethod_ComputeHologram() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ComputeHologram(::grpc::ServerContext* /*context*/, const ::hololibgrpc::HologramRequest* /*request*/, ::hololibgrpc::HologramReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ComputeHologram(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ComputeHologram_stream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ComputeHologram_stream() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->ComputeHologram_stream(context, request); }));
    }
    ~WithRawCallbackMethod_ComputeHologram_stream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ComputeHologram_stream(::grpc::ServerContext* /*context*/, const ::hololibgrpc::HologramRequest* /*request*/, ::grpc::ServerWriter< ::hololibgrpc::HologramReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* ComputeHologram_stream(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SayHello() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::hololibgrpc::HelloRequest, ::hololibgrpc::HelloReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::hololibgrpc::HelloRequest, ::hololibgrpc::HelloReply>* streamer) {
                       return this->StreamedSayHello(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::hololibgrpc::HelloRequest* /*request*/, ::hololibgrpc::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSayHello(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::hololibgrpc::HelloRequest,::hololibgrpc::HelloReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SayHelloAgain : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SayHelloAgain() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::hololibgrpc::HelloRequest, ::hololibgrpc::HelloReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::hololibgrpc::HelloRequest, ::hololibgrpc::HelloReply>* streamer) {
                       return this->StreamedSayHelloAgain(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SayHelloAgain() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SayHelloAgain(::grpc::ServerContext* /*context*/, const ::hololibgrpc::HelloRequest* /*request*/, ::hololibgrpc::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSayHelloAgain(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::hololibgrpc::HelloRequest,::hololibgrpc::HelloReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ComputeHologram : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ComputeHologram() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::hololibgrpc::HologramRequest, ::hololibgrpc::HologramReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::hololibgrpc::HologramRequest, ::hololibgrpc::HologramReply>* streamer) {
                       return this->StreamedComputeHologram(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ComputeHologram() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ComputeHologram(::grpc::ServerContext* /*context*/, const ::hololibgrpc::HologramRequest* /*request*/, ::hololibgrpc::HologramReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedComputeHologram(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::hololibgrpc::HologramRequest,::hololibgrpc::HologramReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SayHello<WithStreamedUnaryMethod_SayHelloAgain<WithStreamedUnaryMethod_ComputeHologram<Service > > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_ComputeHologram_stream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_ComputeHologram_stream() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::hololibgrpc::HologramRequest, ::hololibgrpc::HologramReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::hololibgrpc::HologramRequest, ::hololibgrpc::HologramReply>* streamer) {
                       return this->StreamedComputeHologram_stream(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_ComputeHologram_stream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ComputeHologram_stream(::grpc::ServerContext* /*context*/, const ::hololibgrpc::HologramRequest* /*request*/, ::grpc::ServerWriter< ::hololibgrpc::HologramReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedComputeHologram_stream(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::hololibgrpc::HologramRequest,::hololibgrpc::HologramReply>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_ComputeHologram_stream<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_SayHello<WithStreamedUnaryMethod_SayHelloAgain<WithStreamedUnaryMethod_ComputeHologram<WithSplitStreamingMethod_ComputeHologram_stream<Service > > > > StreamedService;
};

}  // namespace hololibgrpc


#endif  // GRPC_hololib_2eproto__INCLUDED
