// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: hololib.proto

#include "hololib.pb.h"
#include "hololib.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace hololibgrpc {

static const char* Greeter_method_names[] = {
  "/hololibgrpc.Greeter/SayHello",
  "/hololibgrpc.Greeter/SayHelloAgain",
  "/hololibgrpc.Greeter/ComputeHologram",
  "/hololibgrpc.Greeter/ComputeHologram_stream",
};

std::unique_ptr< Greeter::Stub> Greeter::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Greeter::Stub> stub(new Greeter::Stub(channel, options));
  return stub;
}

Greeter::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SayHello_(Greeter_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SayHelloAgain_(Greeter_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ComputeHologram_(Greeter_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ComputeHologram_stream_(Greeter_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status Greeter::Stub::SayHello(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest& request, ::hololibgrpc::HelloReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hololibgrpc::HelloRequest, ::hololibgrpc::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SayHello_, context, request, response);
}

void Greeter::Stub::async::SayHello(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest* request, ::hololibgrpc::HelloReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hololibgrpc::HelloRequest, ::hololibgrpc::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, std::move(f));
}

void Greeter::Stub::async::SayHello(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest* request, ::hololibgrpc::HelloReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hololibgrpc::HelloReply>* Greeter::Stub::PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hololibgrpc::HelloReply, ::hololibgrpc::HelloRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SayHello_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hololibgrpc::HelloReply>* Greeter::Stub::AsyncSayHelloRaw(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSayHelloRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Greeter::Stub::SayHelloAgain(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest& request, ::hololibgrpc::HelloReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hololibgrpc::HelloRequest, ::hololibgrpc::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SayHelloAgain_, context, request, response);
}

void Greeter::Stub::async::SayHelloAgain(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest* request, ::hololibgrpc::HelloReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hololibgrpc::HelloRequest, ::hololibgrpc::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHelloAgain_, context, request, response, std::move(f));
}

void Greeter::Stub::async::SayHelloAgain(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest* request, ::hololibgrpc::HelloReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHelloAgain_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hololibgrpc::HelloReply>* Greeter::Stub::PrepareAsyncSayHelloAgainRaw(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hololibgrpc::HelloReply, ::hololibgrpc::HelloRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SayHelloAgain_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hololibgrpc::HelloReply>* Greeter::Stub::AsyncSayHelloAgainRaw(::grpc::ClientContext* context, const ::hololibgrpc::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSayHelloAgainRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Greeter::Stub::ComputeHologram(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest& request, ::hololibgrpc::HologramReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hololibgrpc::HologramRequest, ::hololibgrpc::HologramReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ComputeHologram_, context, request, response);
}

void Greeter::Stub::async::ComputeHologram(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest* request, ::hololibgrpc::HologramReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hololibgrpc::HologramRequest, ::hololibgrpc::HologramReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ComputeHologram_, context, request, response, std::move(f));
}

void Greeter::Stub::async::ComputeHologram(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest* request, ::hololibgrpc::HologramReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ComputeHologram_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hololibgrpc::HologramReply>* Greeter::Stub::PrepareAsyncComputeHologramRaw(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hololibgrpc::HologramReply, ::hololibgrpc::HologramRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ComputeHologram_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hololibgrpc::HologramReply>* Greeter::Stub::AsyncComputeHologramRaw(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncComputeHologramRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::hololibgrpc::HologramReply>* Greeter::Stub::ComputeHologram_streamRaw(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::hololibgrpc::HologramReply>::Create(channel_.get(), rpcmethod_ComputeHologram_stream_, context, request);
}

void Greeter::Stub::async::ComputeHologram_stream(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest* request, ::grpc::ClientReadReactor< ::hololibgrpc::HologramReply>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::hololibgrpc::HologramReply>::Create(stub_->channel_.get(), stub_->rpcmethod_ComputeHologram_stream_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::hololibgrpc::HologramReply>* Greeter::Stub::AsyncComputeHologram_streamRaw(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::hololibgrpc::HologramReply>::Create(channel_.get(), cq, rpcmethod_ComputeHologram_stream_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::hololibgrpc::HologramReply>* Greeter::Stub::PrepareAsyncComputeHologram_streamRaw(::grpc::ClientContext* context, const ::hololibgrpc::HologramRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::hololibgrpc::HologramReply>::Create(channel_.get(), cq, rpcmethod_ComputeHologram_stream_, context, request, false, nullptr);
}

Greeter::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::hololibgrpc::HelloRequest, ::hololibgrpc::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hololibgrpc::HelloRequest* req,
             ::hololibgrpc::HelloReply* resp) {
               return service->SayHello(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::hololibgrpc::HelloRequest, ::hololibgrpc::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hololibgrpc::HelloRequest* req,
             ::hololibgrpc::HelloReply* resp) {
               return service->SayHelloAgain(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::hololibgrpc::HologramRequest, ::hololibgrpc::HologramReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hololibgrpc::HologramRequest* req,
             ::hololibgrpc::HologramReply* resp) {
               return service->ComputeHologram(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[3],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< Greeter::Service, ::hololibgrpc::HologramRequest, ::hololibgrpc::HologramReply>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hololibgrpc::HologramRequest* req,
             ::grpc::ServerWriter<::hololibgrpc::HologramReply>* writer) {
               return service->ComputeHologram_stream(ctx, req, writer);
             }, this)));
}

Greeter::Service::~Service() {
}

::grpc::Status Greeter::Service::SayHello(::grpc::ServerContext* context, const ::hololibgrpc::HelloRequest* request, ::hololibgrpc::HelloReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::SayHelloAgain(::grpc::ServerContext* context, const ::hololibgrpc::HelloRequest* request, ::hololibgrpc::HelloReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::ComputeHologram(::grpc::ServerContext* context, const ::hololibgrpc::HologramRequest* request, ::hololibgrpc::HologramReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::ComputeHologram_stream(::grpc::ServerContext* context, const ::hololibgrpc::HologramRequest* request, ::grpc::ServerWriter< ::hololibgrpc::HologramReply>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace hololibgrpc

